
// Assuming your JSON data is stored in a variable called 'jsonString'
var jsonString = '{"key1": "value1", "key2": "value2", "key3": {"nested_key": "nested_value"}}';

// Parse the JSON data
var jsonData = JSON.parse(jsonString);

// Extract all keys
var allKeys = extractKeys(jsonData);

console.log(allKeys);






console.log(fields.build(), "All Fields in getFields");  // Add this line

i  this console i am getting this type of result 

[ { name: '0_id',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.id',
    dataType: 'STRING' },
  { dataType: 'STRING',
    name: '0_name',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.name' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.username',
    dataType: 'STRING',
    name: '0_username' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    name: '0_email',
    label: '0.email' },
  { label: '0.address.street',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: '0_address_street' },
  { semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    label: '0.address.suite',
    dataType: 'STRING',
    name: '0_address_suite' },
  { name: '0_address_city',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.address.city' },
  { label: '0.address.zipcode',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: '0_address_zipcode' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.address.geo.lat',
    dataType: 'STRING',
    name: '0_address_geo_lat' },
  { dataType: 'STRING',
    label: '0.address.geo.lng',
    name: '0_address_geo_lng',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' } },
  { name: '0_phone',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    label: '0.phone' },
  { dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.website',
    name: '0_website' },
  { name: '0_company_name',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '0.company.name',
    dataType: 'STRING' },
  { semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    label: '0.company.catchPhrase',
    name: '0_company_catchPhrase',
    dataType: 'STRING' },
  { semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    dataType: 'STRING',
    name: '0_company_bs',
    label: '0.company.bs' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    label: '1.id',
    name: '1_id' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: '1_name',
    label: '1.name',
    dataType: 'STRING' },
  { dataType: 'STRING',
    name: '1_username',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '1.username' },
  { label: '1.email',
    semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    dataType: 'STRING',
    name: '1_email' },
  { label: '1.address.street',
    name: '1_address_street',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' } },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    name: '1_address_suite',
    label: '1.address.suite' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    label: '1.address.city',
    name: '1_address_city' },
  { label: '1.address.zipcode',
    name: '1_address_zipcode',
    semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    dataType: 'STRING' },
  { label: '1.address.geo.lat',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: '1_address_geo_lat',
    dataType: 'STRING' },
  { dataType: 'STRING',
    semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    name: '1_address_geo_lng',
    label: '1.address.geo.lng' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: '1_phone',
    label: '1.phone',
    dataType: 'STRING' },
  { dataType: 'STRING',
    name: '1_website',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '1.website' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: '1.company.name',
    dataType: 'STRING',
    name: '1_company_name' },
  { dataType: 'STRING',
    semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    label: '1.company.catchPhrase',
    name: '1_company_catchPhrase' },
  { label: '1.company.bs',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    name: '1_company_bs' }]

instead i want 


[ { name: 'id',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'id',
    dataType: 'STRING' },
  { dataType: 'STRING',
    name: 'name',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'name' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'username',
    dataType: 'STRING',
    name: 'username' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    name: 'email',
    label: 'email' },
  { label: 'address.street',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: 'address_street' },
  { semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    label: 'address.suite',
    dataType: 'STRING',
    name: 'address_suite' },
  { name: 'address_city',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'address.city' },
  { label: 'address.zipcode',
    dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    name: 'address_zipcode' },
  { semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'address.geo.lat',
    dataType: 'STRING',
    name: 'address_geo_lat' },
  { dataType: 'STRING',
    label: 'address.geo.lng',
    name: 'address_geo_lng',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' } },
  { name: 'phone',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    dataType: 'STRING',
    label: 'phone' },
  { dataType: 'STRING',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'website',
    name: 'website' },
  { name: 'company_name',
    semantics: { semanticType: 'TEXT', conceptType: 'DIMENSION' },
    label: 'company.name',
    dataType: 'STRING' },
  { semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    label: 'company.catchPhrase',
    name: 'company_catchPhrase',
    dataType: 'STRING' },
  { semantics: { conceptType: 'DIMENSION', semanticType: 'TEXT' },
    dataType: 'STRING',
    name: 'company_bs',
    label: 'company.bs' }]